---
- name: Set Docker to use systemd cgroups driver
  copy:
    dest: "/etc/docker/daemon.json"
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: Restart Docker
  service:
    name: docker
    state: restarted


- name: Initialize Kubernetes cluster
  #command: "kubeadm init --pod-network-cidr {{ pod_cidr }}"
  command: "kubeadm init --pod-network-cidr {{ pod_cidr }} --control-plane-endpoint {{ ansible_host }}:6443 --apiserver-advertise-address {{ ansible_host }} --apiserver-cert-extra-sans {{ ansible_host }}"
  #command: "kubeadm init --pod-network-cidr {{ pod_cidr }} --control-plane-endpoint \"{{ ansible_host }}:6443\" --upload-certs"
  args:
    creates: /etc/kubernetes/admin.conf  # Skip this task if the file already exists
  register: kube_init

- name: Show kube init info
  debug:
    var: kube_init


- name: Create .kube directory in user home
  file:
    path: "{{ home_dir }}/.kube"
    state: directory
    owner: 1000
    group: 1000

- name: Configure .kube/config files in user home
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ home_dir }}/.kube/config"
    remote_src: yes
    owner: 1000
    group: 1000


- name: Restart kubelet for config changes
  service:
    name: kubelet
    state: restarted

- name: Get Calico networking
  get_url:
    url: https://projectcalico.docs.tigera.io/manifests/calico.yaml
    dest: "{{ home_dir }}/calico.yaml"

- name: Apply Calico networking
  become: no
  command: kubectl apply -f "{{ home_dir }}/calico.yaml"

- name: Get Kubernetes Dashboard
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.5.0/aio/deploy/recommended.yaml
    dest: "{{ home_dir }}/dashboard.yaml"

- name: Apply Kubernetes Dashboard
  become: no
  command: kubectl apply -f "{{ home_dir }}/dashboard.yaml"
