---

all:
  children:
    kube_server:
      hosts:
        k8s-1:
          ansible_host: "{{ foo.base_host_ip }}.{{ foo.start_host_ip + 1 }}"
    kube_agents:
      hosts:
        k8s-2:
          ansible_host: "{{ foo.base_host_ip }}.{{ foo.start_host_ip + 2 }}"
        k8s-3:
          ansible_host: "{{ foo.base_host_ip }}.{{ foo.start_host_ip + 3 }}"

