---

- name: Test
  command: "kubectl get nodes -o wide"
  register: out
  become: no

- name: Debug
  debug: var=out


- name: Download Flannel YAML
  get_url:
    url: "https://raw.githubusercontent.com/coreos/flannel/v{{ FLANNEL_VERSION }}/Documentation/kube-flannel.yml"
    dest: "{{ HOME_DIR }}/flannel.yaml"

- name: Apply Flannel Network
  command: kubectl apply -f "{{ HOME_DIR }}/flannel.yaml"
  become: no

- name: Test
  command: "kubectl get pods -A"
  register: out
  become: no

- name: Debug
  debug: var=out


