---

# Common - a

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Add entries to /etc/hosts (master node)
  lineinfile:
    path: /etc/hosts
    line: "{{ IP_NW }}{{ item }} master-node"

- name: Add entries to /etc/hosts (worker nodes)
  lineinfile:
    path: /etc/hosts
    line: "{{ IP_NW }}{{ item }} worker-node{{ item }}"
  with_sequence: start={{ IP_START }} end={{ IP_START + NUM_WORKER_NODES }}

- name: Display /etc/hosts contents
      command: cat /etc/hosts
      register: command_output
      
- debug:
    msg: "{{ command_output.stdout }}"
