---
settings:
  env: 'agus'
  users:
    agus:
      home_dir: /home/vagrant
      ssh:
        user: "vagrant"
        password: "vagrant"
        private_key_path: /home/aagustin/.ssh/vagrant_key
        public_key_path: /home/aagustin/.ssh/vagrant_key

      nodes:
        control:
          cpu: 2
          memory: 4096
        workers:
          count: 1
          cpu: 2
          memory: 4096
      
      network:
        control_ip: 10.0.0.10
        dns_servers:
          - 8.8.8.8
          - 1.1.1.1
        pod_cidr: 172.16.1.0/16
        service_cidr: 172.17.1.0/18
      
      cluster_name: Kubernetes Cluster

      software:
        box: bento/ubuntu-22.04
        calico: 3.25.0
        kubernetes: 1.26.1-00
        os: xUbuntu_22.04
    
    user_n:
      home_dir: /home/vagrant
      ssh:
        user: "vagrant"
        password: "vagrant"
        private_key_path: /home/aagustin/.ssh/vagrant_key
        public_key_path: /home/aagustin/.ssh/vagrant_key

      nodes:
        control:
          cpu: 2
          memory: 4096
        workers:
          count: 1
          cpu: 2
          memory: 4096
      
      network:
        control_ip: 10.0.0.10
        dns_servers:
          - 8.8.8.8
          - 1.1.1.1
        pod_cidr: 172.16.1.0/16
        service_cidr: 172.17.1.0/18
      
      cluster_name: Kubernetes Cluster

      software:
        box: bento/ubuntu-22.04
        calico: 3.25.0
        kubernetes: 1.26.1-00
        os: xUbuntu_22.04
