---
# Profile settings
SETTINGS: "{{ lookup('file', '../../settings.yaml') }}" 
SELECTED_ENV: "{{ SETTINGS.settings.env }}"

## SSH configuration
ansible_ssh_user: "{{ SETTINGS.users[SELECTED_ENV].ssh.user }}"
ansible_ssh_private_key_file: "{{ SETTINGS.users[SELECTED_ENV].ssh.private_key_path }}"
ansible_ssh_pass: "{{ SETTINGS.users[SELECTED_ENV].ssh.password }}"

ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

## Setting up hosts
CONTROL_IP: "{{ SETTINGS.users[SELECTED_ENV].network.control_ip }}"
IP_SECTIONS: "{{ CONTROL_IP | regex_search('^([0-9.]+\\.)([^.]+)$') }}"
IP_NW: "{{ IP_SECTIONS.captures[0] }}"
NUM_WORKER_NODES: "{{ SETTINGS.users[SELECTED_ENV].nodes.workers.count }}"

## Setting up DNS servers
DNS_SERVERS: "{{ SETTINGS.users[SELECTED_ENV].network.dns_servers | join(' ') }}"

## Setting up Kubernetes
KUBERNETES_VERSION: "{{ SETTINGS.users[SELECTED_ENV].software.kubernetes }}"
CALICO_VERSION: "{{ SETTINGS.users[SELECTED_ENV].software.calico }}"
POD_CIDR: "{{ SETTINGS.users[SELECTED_ENV].network.pod_cidr }}"
SERVICE_CIDR: "{{ SETTINGS.users[SELECTED_ENV].network.service_cidr }}"
CLUSTER_NAME: "{{ SETTINGS.users[SELECTED_ENV].cluster_name }}"

## Setting up system variables
OS: "{{ SETTINGS.users[SELECTED_ENV].software.os }}"
ENVIRONMENT: "{{ SETTINGS.users[SELECTED_ENV].environment }}"
HOME_DIR: "{{ SETTINGS.users[SELECTED_ENV].node_home_dir }}"
USER_ID: 1000
GROUP_ID: 1000

