---

all:
  children:
    kube_master:
      hosts:
        master-node-10:
          ansible_host: "{{ CONTROL_IP }}"
    kube_workers:
      hosts:
        worker-node-11:
            ansible_host: "{{ IP_SECTIONS }}11"
