apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.55.51 
      user: root
      port: 22
      keyPath: /home/aagustin/.ssh/vagrant_key
    role: controller
    privateInterface: eth2
  - ssh:
      address: 192.168.55.52
      user: root
      port: 22
      keyPath: /home/aagustin/.ssh/vagrant_key
    role: worker
    privateInterface: eth2
  k0s:
    version: 1.28.2+k0s.0
